[package]
name = "repent"
description = "Placeholder crate"
version = "0.1.0"
edition = "2018"
license = "ISC OR Apache-2.0"
repository = "https://github.com/ergorusty/repent.git"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
